// Shared constant: list of hostel names for dropdown selection and validation.
// Reusable across frontend (Settings, Post, future filter UI) and backend validation.
export const HOSTEL_NAMES = [
  'Agate',
  'Garnet A',
  'Garnet B',
  'Garnet C',
  'Zircon A',
  'Zircon B',
  'Zircon C',
  'Amber A',
  'Amber B',
  'Coral',
  'Aquamarine A',
  'Aquamarine B',
  'Ruby',
  'Emerald',
  'Pearl',
  'Sapphire',
  'Topaz',
  'Lapis',
  'Diamond',
  'Jade',
  'Jasper',
  'Amethyst',
  'Opal A',
  'Opal B',
  'Opal C',
  'Opal D',
  'Opal E',
  'Opal F',
  'Beryl',
];
